# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alejandro/dev/SLAM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alejandro/dev/SLAM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alejandro/dev/SLAM/CMakeFiles /home/alejandro/dev/SLAM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alejandro/dev/SLAM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SLAM

# Build rule for target.
SLAM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SLAM
.PHONY : SLAM

# fast build rule for target.
SLAM/fast:
	$(MAKE) -f CMakeFiles/SLAM.dir/build.make CMakeFiles/SLAM.dir/build
.PHONY : SLAM/fast

#=============================================================================
# Target rules for targets named slam_libs

# Build rule for target.
slam_libs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slam_libs
.PHONY : slam_libs

# fast build rule for target.
slam_libs/fast:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/build
.PHONY : slam_libs/fast

src/debugging.o: src/debugging.cpp.o

.PHONY : src/debugging.o

# target to build an object file
src/debugging.cpp.o:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/debugging.cpp.o
.PHONY : src/debugging.cpp.o

src/debugging.i: src/debugging.cpp.i

.PHONY : src/debugging.i

# target to preprocess a source file
src/debugging.cpp.i:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/debugging.cpp.i
.PHONY : src/debugging.cpp.i

src/debugging.s: src/debugging.cpp.s

.PHONY : src/debugging.s

# target to generate assembly for a file
src/debugging.cpp.s:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/debugging.cpp.s
.PHONY : src/debugging.cpp.s

src/frameProvider.o: src/frameProvider.cpp.o

.PHONY : src/frameProvider.o

# target to build an object file
src/frameProvider.cpp.o:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/frameProvider.cpp.o
.PHONY : src/frameProvider.cpp.o

src/frameProvider.i: src/frameProvider.cpp.i

.PHONY : src/frameProvider.i

# target to preprocess a source file
src/frameProvider.cpp.i:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/frameProvider.cpp.i
.PHONY : src/frameProvider.cpp.i

src/frameProvider.s: src/frameProvider.cpp.s

.PHONY : src/frameProvider.s

# target to generate assembly for a file
src/frameProvider.cpp.s:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/frameProvider.cpp.s
.PHONY : src/frameProvider.cpp.s

src/landmarksManager.o: src/landmarksManager.cpp.o

.PHONY : src/landmarksManager.o

# target to build an object file
src/landmarksManager.cpp.o:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/landmarksManager.cpp.o
.PHONY : src/landmarksManager.cpp.o

src/landmarksManager.i: src/landmarksManager.cpp.i

.PHONY : src/landmarksManager.i

# target to preprocess a source file
src/landmarksManager.cpp.i:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/landmarksManager.cpp.i
.PHONY : src/landmarksManager.cpp.i

src/landmarksManager.s: src/landmarksManager.cpp.s

.PHONY : src/landmarksManager.s

# target to generate assembly for a file
src/landmarksManager.cpp.s:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/landmarksManager.cpp.s
.PHONY : src/landmarksManager.cpp.s

src/slam.o: src/slam.cpp.o

.PHONY : src/slam.o

# target to build an object file
src/slam.cpp.o:
	$(MAKE) -f CMakeFiles/SLAM.dir/build.make CMakeFiles/SLAM.dir/src/slam.cpp.o
.PHONY : src/slam.cpp.o

src/slam.i: src/slam.cpp.i

.PHONY : src/slam.i

# target to preprocess a source file
src/slam.cpp.i:
	$(MAKE) -f CMakeFiles/SLAM.dir/build.make CMakeFiles/SLAM.dir/src/slam.cpp.i
.PHONY : src/slam.cpp.i

src/slam.s: src/slam.cpp.s

.PHONY : src/slam.s

# target to generate assembly for a file
src/slam.cpp.s:
	$(MAKE) -f CMakeFiles/SLAM.dir/build.make CMakeFiles/SLAM.dir/src/slam.cpp.s
.PHONY : src/slam.cpp.s

src/tracking.o: src/tracking.cpp.o

.PHONY : src/tracking.o

# target to build an object file
src/tracking.cpp.o:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/tracking.cpp.o
.PHONY : src/tracking.cpp.o

src/tracking.i: src/tracking.cpp.i

.PHONY : src/tracking.i

# target to preprocess a source file
src/tracking.cpp.i:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/tracking.cpp.i
.PHONY : src/tracking.cpp.i

src/tracking.s: src/tracking.cpp.s

.PHONY : src/tracking.s

# target to generate assembly for a file
src/tracking.cpp.s:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/src/tracking.cpp.s
.PHONY : src/tracking.cpp.s

thirdparty/tum_reader/src/FOVUndistorter.o: thirdparty/tum_reader/src/FOVUndistorter.cpp.o

.PHONY : thirdparty/tum_reader/src/FOVUndistorter.o

# target to build an object file
thirdparty/tum_reader/src/FOVUndistorter.cpp.o:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/thirdparty/tum_reader/src/FOVUndistorter.cpp.o
.PHONY : thirdparty/tum_reader/src/FOVUndistorter.cpp.o

thirdparty/tum_reader/src/FOVUndistorter.i: thirdparty/tum_reader/src/FOVUndistorter.cpp.i

.PHONY : thirdparty/tum_reader/src/FOVUndistorter.i

# target to preprocess a source file
thirdparty/tum_reader/src/FOVUndistorter.cpp.i:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/thirdparty/tum_reader/src/FOVUndistorter.cpp.i
.PHONY : thirdparty/tum_reader/src/FOVUndistorter.cpp.i

thirdparty/tum_reader/src/FOVUndistorter.s: thirdparty/tum_reader/src/FOVUndistorter.cpp.s

.PHONY : thirdparty/tum_reader/src/FOVUndistorter.s

# target to generate assembly for a file
thirdparty/tum_reader/src/FOVUndistorter.cpp.s:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/thirdparty/tum_reader/src/FOVUndistorter.cpp.s
.PHONY : thirdparty/tum_reader/src/FOVUndistorter.cpp.s

thirdparty/tum_reader/src/PhotometricUndistorter.o: thirdparty/tum_reader/src/PhotometricUndistorter.cpp.o

.PHONY : thirdparty/tum_reader/src/PhotometricUndistorter.o

# target to build an object file
thirdparty/tum_reader/src/PhotometricUndistorter.cpp.o:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/thirdparty/tum_reader/src/PhotometricUndistorter.cpp.o
.PHONY : thirdparty/tum_reader/src/PhotometricUndistorter.cpp.o

thirdparty/tum_reader/src/PhotometricUndistorter.i: thirdparty/tum_reader/src/PhotometricUndistorter.cpp.i

.PHONY : thirdparty/tum_reader/src/PhotometricUndistorter.i

# target to preprocess a source file
thirdparty/tum_reader/src/PhotometricUndistorter.cpp.i:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/thirdparty/tum_reader/src/PhotometricUndistorter.cpp.i
.PHONY : thirdparty/tum_reader/src/PhotometricUndistorter.cpp.i

thirdparty/tum_reader/src/PhotometricUndistorter.s: thirdparty/tum_reader/src/PhotometricUndistorter.cpp.s

.PHONY : thirdparty/tum_reader/src/PhotometricUndistorter.s

# target to generate assembly for a file
thirdparty/tum_reader/src/PhotometricUndistorter.cpp.s:
	$(MAKE) -f CMakeFiles/slam_libs.dir/build.make CMakeFiles/slam_libs.dir/thirdparty/tum_reader/src/PhotometricUndistorter.cpp.s
.PHONY : thirdparty/tum_reader/src/PhotometricUndistorter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SLAM"
	@echo "... slam_libs"
	@echo "... src/debugging.o"
	@echo "... src/debugging.i"
	@echo "... src/debugging.s"
	@echo "... src/frameProvider.o"
	@echo "... src/frameProvider.i"
	@echo "... src/frameProvider.s"
	@echo "... src/landmarksManager.o"
	@echo "... src/landmarksManager.i"
	@echo "... src/landmarksManager.s"
	@echo "... src/slam.o"
	@echo "... src/slam.i"
	@echo "... src/slam.s"
	@echo "... src/tracking.o"
	@echo "... src/tracking.i"
	@echo "... src/tracking.s"
	@echo "... thirdparty/tum_reader/src/FOVUndistorter.o"
	@echo "... thirdparty/tum_reader/src/FOVUndistorter.i"
	@echo "... thirdparty/tum_reader/src/FOVUndistorter.s"
	@echo "... thirdparty/tum_reader/src/PhotometricUndistorter.o"
	@echo "... thirdparty/tum_reader/src/PhotometricUndistorter.i"
	@echo "... thirdparty/tum_reader/src/PhotometricUndistorter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

